### ISSUE TITLE
Missing Excel file

### ISSUE THREAD

**Issue by braymp** [carpenterlab/2016_bray_natprot#2]
Apparently, the Excel file mentioned under https://github.com/carpenterlab/2016_bray_natprot/wiki#alternate-stains is missing (I get a 404 error)

**Comment by shntnu** [comment]
Odd – I'm no longer able to locate the file (in the repo that is).

**Comment by face-palm** [comment]
@braymp @shntnu @AnneCarpenter any chance this file was ever located?

**Comment by shntnu** [comment]
Fixed in #5 #6
