### ISSUE TITLE
Cell Painting feature extraction - FAST way

### ISSUE THREAD

**Issue by 32nguyen** [carpenterlab/2016_bray_natprot#4]
Hi,
I am from Electrical Engineering field and completely new with CellProfiler. At the moment, I have to calculate the Cell Painting Features as you mentioned. There are 1783 features.

I wonder if there is a available completed way to run a single script that can extract these 1783 features from a group of 5 channels of fluorescent images.

Any help would be appreciated.

Thanks

**Comment by shntnu** [comment]
I assume you've already looked up how to do it using CellProfiler?
