### ISSUE TITLE
Excel file with alternative stains tested assay development not found

### ISSUE THREAD

**Issue by kyliefogarty** [carpenterlab/2016_bray_natprot#5]
Not exactly a new issue, it is the same from 2018 but it has been a while so figured I'd try again :)
The Excel file in "alternative stains" that should contain "notes during the development of the assay that might be helpful if you are trying to adapt it" is not found.  (error 404).  Does anyone have access to the info it contains to share it in a different way?

**Comment by shntnu** [comment]
Found it!

https://github.com/carpenterlab/2016_bray_natprot/wiki/Home/_compare/bef048e39a15039b08dfafcba0abab97f68bc9c7...67f9afa56618e3ec1624e91f7fcc0e89afc96b0e

**Comment by shntnu** [comment]
To clarify – the file is now here https://github.com/carpenterlab/2016_bray_natprot/blob/master/supplementary_files/stains_development_notes.md
